#!/usr/bin/python3
"""
THIS FILE CONTAINS THE LOOKUP FUNC.
THAT RETURNS THE LIST  OF AVALILABLE
ATTRIBUTES&METHODS IN AN OBJ."""


def lookup(obj):
    """Defining THE LOOKUP FUNC. WHICH RETURNS THE LIST  OF AVALILABLE
    ATTRIBUTES&METHODS IN AN OBJ."""
    return dir(obj)
